import type { GearSet, Provenance } from '@xiv-gear-lab/domain';

export const communitySourcesForResult = (set: GearSet): Provenance[] => [...new Map(
  set.provenance
    .filter((entry) => entry.kind === 'community-curated')
    .map((entry) => [`${entry.provider}:${entry.sourceUrl ?? entry.providerRecordId ?? ''}`, entry])
).values()];

export const resultMethodologyDescription = (set: GearSet, communitySources = communitySourcesForResult(set)) => {
  const usedCuratedWarmStart = set.origin === 'generated' && communitySources.length > 0;
  if (set.origin === 'curated') return 'Community-curated set, recalculated locally when calculation context is present.';
  if (usedCuratedWarmStart) return 'Independently recalculated generated result; a known community set entered the same legal candidate pool as a warm start.';
  if (set.origin === 'generated') return 'Independently generated by XIV Gear Lab from the allowed item pool.';
  if (set.origin === 'custom') return 'User-modified local hypothetical result.';
  return 'Locally saved result; its pinned calculation context is shown below.';
};
